#!/usr/bin/env python3
"""Reconcile the archived r2-shaped extraction against the r3 catalog.

`archive/stig/nist_800_171r3_stig.json` and the playbook in `archive/os/`
carry NIST SP 800-171 *r2* titles on *r3* requirement IDs. Anything tagged
from them maps to the wrong control, or to a control that no longer exists.

This regenerates `docs/legacy-gap.md` from the current catalog so the record
stays checkable rather than inherited:

    ./tools/legacy-gap.py            # rewrite docs/legacy-gap.md
    ./tools/legacy-gap.py --stdout   # print without writing
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog" / "requirements.json"
LEGACY = ROOT.parent / "archive" / "stig" / "nist_800_171r3_stig.json"
OUT = ROOT / "docs" / "legacy-gap.md"


def load() -> tuple[dict, dict]:
    if not CATALOG.exists():
        sys.exit(f"missing {CATALOG} — run `make catalog`")
    if not LEGACY.exists():
        sys.exit(f"missing {LEGACY} — the archived extraction is gone; "
                 "delete this tool and docs/legacy-gap.md with it")
    cat = {e["id"]: e for e in json.loads(CATALOG.read_text())["requirements"]}
    leg = {f["id"]: f for f in json.loads(LEGACY.read_text())["findings"]}
    return cat, leg


def render(cat: dict, leg: dict) -> str:
    active = {i for i, e in cat.items() if not e["withdrawn"]}
    withdrawn = {i for i, e in cat.items() if e["withdrawn"]}

    kept = sorted(withdrawn & set(leg))
    missing = sorted(active - set(leg))
    retitled = [
        (i, leg[i]["title"].strip(), cat[i]["title"].strip())
        for i in sorted(active & set(leg))
        if leg[i]["title"].strip().lower() != cat[i]["title"].strip().lower()
    ]
    aligned = len(active & set(leg)) - len(retitled)

    L = []
    w = L.append
    w("# Why the archived trees are not the catalog of record")
    w("")
    w("Generated by `tools/legacy-gap.py` from `catalog/requirements.json`")
    w("(itself extracted from the publication PDF) against")
    w("`../archive/stig/nist_800_171r3_stig.json`. Regenerate with:")
    w("")
    w("```bash")
    w("./tools/legacy-gap.py")
    w("```")
    w("")
    w("`archive/stig/` and `archive/os/` are an r2-shaped extraction wearing r3")
    w("requirement IDs. They are a useful command scrapbook and nothing more.")
    w("This file is the migration record: it exists so that anyone reading the")
    w("archived trees knows which of their tags point at the wrong control.")
    w("")
    w("| Finding | N |")
    w("| --- | ---: |")
    w(f"| Legacy entries | {len(leg)} |")
    w(f"| Same ID, same title | {aligned} |")
    w(f"| Same ID, different requirement | {len(retitled)} |")
    w(f"| Withdrawn in r3, still listed as live | {len(kept)} |")
    w(f"| Active in r3, absent from the extraction | {len(missing)} |")
    w("")

    w("## Withdrawn in r3, still live in the extraction")
    w("")
    w(f"{len(kept)} IDs. A playbook task tagged with any of these implements a")
    w("requirement that r3 does not have, and will map to nothing in an")
    w("assessment.")
    w("")
    for n in range(0, len(kept), 6):
        w("`" + "` `".join(kept[n:n + 6]) + "`")
    w("")

    w("## Active in r3, absent from the extraction")
    w("")
    w(f"{len(missing)} requirements the legacy tree cannot satisfy because it")
    w("does not know they exist — including the whole of 03.15 Planning,")
    w("03.16 System and Services Acquisition, and 03.17 Supply Chain Risk")
    w("Management, which are new in r3.")
    w("")
    w("| ID | r3 title |")
    w("| --- | --- |")
    for i in missing:
        w(f"| `{i}` | {cat[i]['title']} |")
    w("")

    w("## Same ID, different requirement")
    w("")
    w(f"{len(retitled)} IDs where the extraction and r3 disagree about what the")
    w("requirement *is*. These are the dangerous ones: the tag looks valid, the")
    w("control it enforces is not the control the ID names.")
    w("")
    w("| ID | Legacy thought it was | r3 actually is |")
    w("| --- | --- | --- |")
    for i, a, b in retitled:
        w(f"| `{i}` | {a} | **{b}** |")
    w("")

    w("## Consequences worth restating")
    w("")
    w("- Multi-factor authentication is `03.05.03`. The extraction puts it at")
    w("  `03.05.02`, which in r3 is Device Identification and Authentication.")
    w("- `03.14.07` is withdrawn. The archived playbook uses it for AIDE;")
    w("  file integrity monitoring belongs under `03.14.06` System Monitoring.")
    w("- `03.13.11` is Cryptographic Protection, not Session Authenticity")
    w("  (`03.13.15`). The nginx snippet in `web/` cited the wrong one.")
    w("- `google-authenticator` is not FIPS 140-3 validated, so it does not")
    w("  satisfy `03.05.03` on a host running in FIPS mode.")
    w("- The archived playbook POSTs telemetry to a placeholder URL. No r3")
    w("  requirement asks for that.")
    w("")
    return "\n".join(L) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = p.parse_args()

    cat, leg = load()
    text = render(cat, leg)
    if args.stdout:
        sys.stdout.write(text)
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
